name: CI

on:
  push:
    branches:
      - main
      - master
      - develop
  pull_request:
    branches:
      - main
      - master
      - develop
  workflow_dispatch:

jobs:
  verify:
    name: Verify Parent POM
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [17, 21]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Temurin JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
          cache: maven

      - name: Build parent POM
        run: mvn -B -ntp clean install

      - name: Check display-updates profile
        run: mvn -B -ntp -Pdisplay-updates help:active-profiles

  release-config:
    name: Release Configuration Check
    runs-on: ubuntu-latest
    needs: verify
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Validate sonatype-oss-release profile
        run: mvn -B -ntp -Psonatype-oss-release -Dgpg.skip=true help:active-profiles
