name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:
    inputs:
      version:
        description: "Release version (major only, e.g. 2)"
        required: true
        type: string

jobs:
  release:
    name: Publish Parent POM
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up Temurin JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21
          cache: maven
          server-id: sonatype-oss-release
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE

      - name: Configure Git author
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git

      - name: Verify parent build
        run: mvn -B -ntp clean install

      - name: Prepare and perform release (manual trigger)
        if: github.event_name == 'workflow_dispatch'
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          set -euo pipefail
          RELEASE="${{ github.event.inputs.version }}"
          NEXT=$((RELEASE + 1))
          mvn -B -ntp release:clean release:prepare release:perform \
            -DreleaseVersion="$RELEASE" \
            -DdevelopmentVersion="${NEXT}-SNAPSHOT" \
            -Dtag="v$RELEASE" \
            -Darguments="-DskipTests"

      - name: Push release commits
        if: github.event_name == 'workflow_dispatch'
        run: git push origin --follow-tags

      - name: Create GitHub release
        if: github.event_name == 'workflow_dispatch'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          name: Opinion Parent v${{ github.event.inputs.version }}
          body: |
            🚀 **Opinion Parent v${{ github.event.inputs.version }}**

            The parent POM has been published to Maven Central. Use it by updating your module parent declaration:

            ```xml
            <parent>
              <groupId>com.inqwise.opinion</groupId>
              <artifactId>opinion-parent</artifactId>
              <version>${{ github.event.inputs.version }}</version>
            </parent>
            ```

            *Next development version: $(( ${{ github.event.inputs.version }} + 1 ))-SNAPSHOT*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Maven Central (tag-based release)
        if: github.event_name == 'release'
        env:
          MAVEN_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: |
          mvn -B -ntp clean deploy -Psonatype-oss-release -DskipTests
